GET https://flower-store-reboot-4abaf6016485.herokuapp.com/api/flowers

###
POST https://flower-store-reboot-4abaf6016485.herokuapp.com/api/flowers
Content-Type: application/json

{
  "sepalLength": 100.0,
  "color": "BLUE",
  "price": 100.0,
  "flowerType": "TULIP"
}